name: build

on:
  push:
    branches:
      - main
      - dev*
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    name: Ruby 3.3 (macOS)
    steps:
    - uses: actions/checkout@v4
    - name: Install llama.cpp
      run: |
        brew update
        brew install llama.cpp
        brew info llama.cpp
    - name: Set up Ruby 3.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Build and test with Rake
      run: |
        bundle exec rake compile -- --with-opt-dir=/opt/homebrew
        bundle exec rake test
